"""VisualForge validator package.

Re-exports all check functions and provides run_mid_run_checks and
run_full_checks orchestrators. The entry point in scripts/validate_design_docs.py
imports from here.

Generated by scripts/_split_validators.py — do not hand-edit structure.
"""
from __future__ import annotations

from pathlib import Path

from ._common import (
    Findings,
    REQUIRED_DOCS,
    REQUIRED_AUDITABILITY,
    REQUIRED_TOKENS,
    ROOT_ALLOWED,
    SUBSKILL_DEC_RANGES,
    SKILL_DEC_CROSS_REFS,
)
from .structural import check_required_files
from .structural import check_persona_files
from .structural import check_concurrency_lock
from .structural import check_figma_artifacts
from .structural import check_version_stamps
from .structural import check_whats_missing
from .structural import check_retrofit_data_awareness
from .tokens import check_token_integrity
from .tokens import check_no_raw_values_in_components
from .tokens import check_dark_mode_coverage
from .dec_integrity import check_strict_dec_shape
from .dec_integrity import check_decision_log
from .dec_integrity import check_decision_id_resolution
from .dec_integrity import check_decision_id_singleton
from .dec_integrity import check_per_dec_metadata
from .dec_integrity import check_persona_dec_consistency
from .dec_integrity import check_dec_range_allocation
from .claim_discipline import check_forbidden_ambiguity
from .claim_discipline import check_numeric_claim_labels
from .claim_discipline import check_raw_px_in_layout_and_components
from .claim_discipline import check_hedge_on_known_values
from .claim_discipline import check_cross_subskill_cites
from .semantic_drift import check_implementation_mutation_log
from .semantic_drift import check_wrapper_semantic_drift
from .visual_defaults import check_visual_default_breakers
from .visual_defaults import check_image_art_direction
from .visual_defaults import check_platform_mode_lock
from .visual_defaults import check_visual_direction_lock_complete
from .visual_defaults import check_react_quality_discipline
from .visual_defaults import check_assumption_persona_validation
from .visual_defaults import check_pressure_test_reviewer_coverage
from .visual_defaults import check_timing_token_drift
from .state_pages import check_state_page_cross_cites
from .plugin_contracts import check_plugin_source_contracts
from .color import check_color_decision_basis
from .slop import scan_slop
from .harness import _run_self_test


def run_mid_run_checks(root: Path, findings: Findings) -> None:
    """Fast checks for between-subskill validation. No file-existence enforcement."""
    check_strict_dec_shape(root, findings)
    check_decision_log(root, findings)
    check_decision_id_resolution(root, findings)
    check_decision_id_singleton(root, findings)
    check_per_dec_metadata(root, findings)
    check_persona_dec_consistency(root, findings)
    check_forbidden_ambiguity(root, findings)
    check_raw_px_in_layout_and_components(root, findings)
    check_hedge_on_known_values(root, findings)
    check_cross_subskill_cites(root, findings)
    check_concurrency_lock(root, findings)
    check_implementation_mutation_log(root, findings)
    check_wrapper_semantic_drift(root, findings)
    check_visual_default_breakers(root, findings)
    check_image_art_direction(root, findings)
    check_platform_mode_lock(root, findings)
    check_visual_direction_lock_complete(root, findings)
    check_react_quality_discipline(root, findings)
    check_assumption_persona_validation(root, findings)
    check_pressure_test_reviewer_coverage(root, findings)
    check_timing_token_drift(root, findings)
    check_state_page_cross_cites(root, findings)
    check_dec_range_allocation(root, findings)
    check_plugin_source_contracts(root, findings)
    check_color_decision_basis(root, findings)


def run_full_checks(root: Path, findings: Findings, strict: bool) -> None:
    """All checks plus slop scan. Use post-completion."""
    check_required_files(root, findings)
    flat = check_token_integrity(root, findings)
    check_dark_mode_coverage(flat, findings)
    check_no_raw_values_in_components(root, findings)
    check_strict_dec_shape(root, findings)
    check_decision_log(root, findings)
    check_decision_id_resolution(root, findings)
    check_decision_id_singleton(root, findings)
    check_per_dec_metadata(root, findings)
    check_persona_dec_consistency(root, findings)
    check_persona_files(root, findings)
    check_figma_artifacts(root, findings)
    check_retrofit_data_awareness(root, findings)
    check_forbidden_ambiguity(root, findings)
    check_numeric_claim_labels(root, findings)
    check_raw_px_in_layout_and_components(root, findings)
    check_hedge_on_known_values(root, findings)
    check_cross_subskill_cites(root, findings)
    check_version_stamps(root, findings)
    check_whats_missing(root, findings)
    check_concurrency_lock(root, findings)
    check_implementation_mutation_log(root, findings)
    check_wrapper_semantic_drift(root, findings)
    # v1.8.0
    check_visual_default_breakers(root, findings)
    check_image_art_direction(root, findings)
    check_platform_mode_lock(root, findings)
    check_visual_direction_lock_complete(root, findings)
    check_react_quality_discipline(root, findings)
    check_assumption_persona_validation(root, findings)
    check_pressure_test_reviewer_coverage(root, findings)
    check_timing_token_drift(root, findings)
    check_state_page_cross_cites(root, findings)
    check_dec_range_allocation(root, findings)
    check_plugin_source_contracts(root, findings)
    check_color_decision_basis(root, findings)
    scan_slop(root, findings, strict)
