"""Shared types, constants, regexes, and helpers used by all validator modules.

Generated by scripts/_split_validators.py.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

@dataclass
class Findings:
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def fail(self, msg: str) -> None:
        self.errors.append(msg)

    def warn(self, msg: str) -> None:
        self.warnings.append(msg)

    @property
    def ok(self) -> bool:
        return not self.errors


SLOP_WORDS = {
    "modern", "clean", "minimal", "intuitive", "seamless", "delightful",
    "professional", "user-friendly", "sleek", "elegant", "polished", "vibrant",
    "premium", "pixel-perfect", "beautiful", "smooth", "subtle", "pop",
    "consider", "feels", "nice", "robust", "scalable",
}


FORBIDDEN_AMBIGUITY_PHRASES = [
    "as needed",
    "as appropriate",
    "where appropriate",
    "if applicable",
    "handle edge cases",
    "appropriate spacing",
    "appropriate styling",
    "modern library",
    "modern stack",
    "add proper validation",
    "make it responsive",
    "make it accessible",
    "improve performance",
    "add tests",
    "add documentation",
]


REQUIRED_DOCS = [
    "README.md",
    "RULES.md",
    "00-index.md",
    "01-foundations/design-brief.md",
    "01-foundations/competitive-audit.md",
    "01-foundations/design-trends-research.md",
    "01-foundations/personas/_index.md",
    "02-visual-language/brand-identity.md",
    "02-visual-language/design-tokens.md",
    "02-visual-language/surface-treatments.md",
    "02-visual-language/iconography.md",
    "03-structure/information-architecture.md",
    "03-structure/layout-system.md",
    "03-structure/site-map.md",
    "04-interaction/ux-flows.md",
    "04-interaction/content-design.md",
    "04-interaction/micro-interactions.md",
    "04-interaction/scroll-and-gesture.md",
    "04-interaction/imagery-illustration.md",
    "04-interaction/motion-design.md",
    "04-interaction/data-visualization.md",
    "04-interaction/auth-flows.md",
    "04-interaction/system-pages.md",
    "04-interaction/notifications-and-lifecycle.md",
    "03-structure/mobile-and-responsive.md",
    "03-structure/i18n-rtl.md",
    "05-components/overview.md",
    "05-components/_index.md",
    "06-screens/_index.md",
    "07-quality/accessibility-contract.md",
    "07-quality/frontend-implementation-contract.md",
    "07-quality/design-ops.md",
    "07-quality/design-qa-report.md",
    "07-quality/design-pressure-test-report.md",
]


REQUIRED_AUDITABILITY = [
    "auditability/mode-report.md",
    "auditability/run-log.md",
    "auditability/decision-log.md",
    "auditability/research-ledger.md",
    "auditability/design-quality-review.md",
    "auditability/pressure-test-iterations.md",
    "auditability/rules-update-log.md",
    "auditability/visual-direction-lock.md",  # Added v1.8.0 per VF-FIND-035 (orchestrator Step 0g)
    "auditability/self-pressure-test-report.md",  # Added v1.8.0 per VF-FIND-044 (orchestrator self-distrust step)
]


REQUIRED_TOKENS = [
    "tokens/tokens.json",
    "tokens/tokens.css",
    "tokens/tokens.ts",
    "tokens/tokens.figma.json",
]


# At least one file expected per directory; presence enforced separately
REQUIRED_DIRS_WITH_CONTENT = [
    "01-foundations/personas",   # persona-[slug].md files
    "05-components",             # primitives/composites/patterns subdirs
    "06-screens",                # SCR-NNN-[slug].md files
]


# Allowed files at design-system root (anti flat-dump rule).
# WHATS-MISSING.md belongs at root per check_whats_missing; HOW-TO-READ.md is an optional
# alternative to README.md historically permitted at root.
ROOT_ALLOWED = {"README.md", "RULES.md", "00-index.md", "WHATS-MISSING.md", "HOW-TO-READ.md"}


# Retrofit-mode artifacts (validated only when retrofit/ exists)
RETROFIT_REQUIRED = [
    "retrofit/inventory.md",
    "retrofit/data-inventory.md",
    "retrofit/data-crosswalk.md",
    "retrofit/backend-gaps.md",
    "retrofit/missing-surfaces.md",
    "retrofit/ia-restructuring.md",
    "retrofit/drift-report.md",
    "retrofit/migration-plan.md",
]


HEX_PATTERN = re.compile(r"#[0-9a-fA-F]{3,8}\b")


RAW_PX_PATTERN = re.compile(r"\b\d+(\.\d+)?px\b")


RAW_MS_PATTERN = re.compile(r"\b\d+(\.\d+)?ms\b")


CUBIC_PATTERN = re.compile(r"cubic-bezier\([^)]*\)")


DEC_HEADING_PATTERN = re.compile(r"^###?\s+\[?DEC-\d{3,4}\]?\s", re.MULTILINE)


REF_PATTERN = re.compile(r"^\{([^}]+)\}$")


DEC_ID_PATTERN = re.compile(r"\bDEC-(\d{3,4})\b")


# VF-FIND-005: strict DEC-NNN shape. No suffixes, no underscores, no _icon-style workarounds.
STRICT_DEC_OK = re.compile(r"\bDEC-\d{3,4}\b")


STRICT_DEC_BAD = re.compile(r"\bDEC-\d{3,4}[_-][A-Za-z]+\b|\bDEC-\d{3,4}\.\d+\b|\bDEC-[A-Z]+-\d+\b")


# Note: DEC-NNN.M sub-decisions are explicitly allowed in the protocol (see opinionated-decision-template).
# This regex catches *workaround* shapes: DEC-200_icon, DEC-200-tmp, DEC-CATEGORY-001 (Specforge style).
# Sub-decision pattern DEC-NNN.M is excluded from BAD via separate check below.
STRICT_DEC_SUBDEC = re.compile(r"\bDEC-\d{3,4}\.\d+\b")


VERSION_STAMP_PATTERN = re.compile(
    r"<!--\s*visualforge:\s*v\d+\.\d+\.\d+\s+run-id=\S+\s+scope=\S+\s+generated=\S+\s*-->"
)


CONTRAST_RATIO_PATTERN = re.compile(r"\b\d+(\.\d+)?\s*:\s*1\b")


NUMERIC_LABEL_PATTERN = re.compile(
    r"\((measured|computed|estimated|target|assumption)\b",
    re.IGNORECASE,
)


HEDGE_ON_NUMBER_PATTERN = re.compile(
    r"\b(?:≥|≤|>=|<=|~|approximately|approx\.?|around|about|roughly)\s*\d+",
    re.IGNORECASE,
)


CROSS_CUT_TERMS = [
    "workspace switcher", "primary nav", "side rail", "top bar",
    "command palette", "Cmd+K",
    "taxonomy", "vocabulary", "renewal", "client",
    "WCAG", "accessibility level",
    "brand voice", "voice profile",
    "permission matrix", "role-aware",
    "marketing-app boundary",
    "spacing scale", "type scale", "shadow philosophy",
]


PERSONA_TEMPLATE_A_HEADINGS = {
    "## Identity", "## Context", "## Goals and frustrations",
    "## Accessibility profile", "## Mental model", "## Quote",
    "## Quantitative grounding", "## Day-in-the-life narrative",
    "## Validation plan", "## Decision card",
}


PERSONA_TEMPLATE_B_HEADINGS = {
    "## Identity", "## Context",
    "## Why she's the wrong fit", "## Why he's the wrong fit",
    "## What we are intentionally not building",
    "## Anti-persona is binding",
    "## Decision card",
}


PERSONA_TEMPLATE_C_HEADINGS = {
    "## Relationship", "## Authority asymmetry",
    "## Goal alignment", "## Goal tension",
    "## Touchpoints", "## Trust / privacy line",
    "## Design implications", "## Decision card",
}


_TIMING_TOKEN_DECL_PATTERN = re.compile(
    # Match either:
    #   `duration.fast` 120ms        (token in backticks, then value)
    #   `duration.fast: 120ms`       (token + colon + value inside backticks)
    #   - `duration.fast` 120ms      (list bullet)
    # Capture group 1 = token name; group 2 = numeric ms value.
    r"`(duration\.[a-z-]+)`[^`]{0,40}?(\d+)\s*ms",
    re.IGNORECASE,
)


SUBSKILL_DEC_RANGES = {
    # Subskill name -> (lo, hi) inclusive, per
    # `_visualforge-shared/references/decision-id-allocation.md`. Includes overflow.
    'visualforge-discovery':                   (1, 24),
    'visualforge-user-research':               (25, 49),
    'visualforge-competitive-audit':           (50, 69),
    'visualforge-design-trends-research':      (70, 89),
    'visualforge-brand-identity':              (90, 109),
    'visualforge-design-tokens':               (110, 169),
    'visualforge-surface-treatments':          (170, 199),
    'visualforge-iconography':                 (200, 224),
    'visualforge-information-architecture':    (225, 254),
    'visualforge-layout-system':               (255, 279),
    'visualforge-mobile-and-responsive':       (280, 309),
    'visualforge-i18n-rtl':                    (310, 339),
    'visualforge-ux-flows':                    (340, 409),
    'visualforge-component-system':            (410, 569),
    'visualforge-content-design':              (570, 599),
    'visualforge-micro-interactions':          (600, 639),
    'visualforge-scroll-and-gesture':          (640, 669),
    'visualforge-imagery-illustration':        (670, 699),
    'visualforge-data-visualization':          (700, 729),
    'visualforge-auth-flows':                  (730, 764),
    'visualforge-system-pages':                (765, 789),
    'visualforge-notifications-and-lifecycle': (790, 829),
    'visualforge-accessibility':               (830, 869),
    'visualforge-motion-design':               (870, 904),
    'visualforge-frontend-contract':           (905, 934),
    'visualforge-design-ops':                  (935, 964),
    'visualforge-figma-build':                 (965, 984),
    'visualforge-design-qa':                   (985, 999),
    'visualforge-design-pressure-test':        (1100, 1219),
    'visualforge-agent-rules-update':          (1220, 1244),
}


# DECs that appear inside a SKILL.md but are cross-references to ANOTHER subskill's
# DEC. These should be excluded from the file's own range check.
# Format: subskill -> { dec_int: target_subskill_name }
SKILL_DEC_CROSS_REFS = {
    'visualforge-iconography': {95: 'visualforge-brand-identity', 100: 'visualforge-brand-identity'},
    'visualforge-imagery-illustration': {100: 'visualforge-brand-identity'},
}


def load_tokens(root: Path) -> dict | None:
    tokens_json = root / "tokens" / "tokens.json"
    if not tokens_json.exists():
        return None
    try:
        return json.loads(tokens_json.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return {"__error__": str(exc)}


def flatten_tokens(tokens: dict, prefix: str = "") -> dict[str, str]:
    """Return a flat map of token.path -> value or reference."""
    out: dict[str, str] = {}
    for key, val in tokens.items():
        if key.startswith("$"):
            continue
        path = f"{prefix}.{key}" if prefix else key
        if isinstance(val, dict):
            if "$value" in val:
                value = val["$value"]
                if isinstance(value, list):
                    out[path] = "composite"
                else:
                    out[path] = str(value)
            else:
                out.update(flatten_tokens(val, path))
    return out


def _strip_excluded_contexts(text: str) -> str:
    """Replace fenced code blocks, blockquotes, and 'What we are NOT doing' sections with
    whitespace so the forbidden-phrase scanner only inspects authored prose. Line numbers
    are preserved because we substitute character-for-character whitespace."""
    text = re.sub(r"```[\s\S]*?```", lambda m: " " * len(m.group(0)), text)
    text = re.sub(r"~~~[\s\S]*?~~~", lambda m: " " * len(m.group(0)), text)
    text = re.sub(r"`[^`\n]*`", lambda m: " " * len(m.group(0)), text)
    text = re.sub(r"^>.*$", lambda m: " " * len(m.group(0)), text, flags=re.MULTILINE)
    text = re.sub(
        r"##\s+What we are (intentionally )?NOT doing[\s\S]*?(?=\n##\s|\Z)",
        lambda m: " " * len(m.group(0)),
        text,
        flags=re.IGNORECASE,
    )
    return text


def _strip_jsx_comments(text: str) -> str:
    """Strip JS/TS/JSX comments before JSX-shape regex matching.

    Purpose: prevent JSX-shape regexes (e.g. `<h1`, `<Button`) from matching
    tokens that appear inside `/** ... */` docstrings or `// ...` line
    comments. Without this, a docstring that describes the page's
    pre-migration `<h1>` would falsely satisfy `has_raw_h1` checks — exactly
    the regression that motivated this helper.

    Design choices (all driven by correctness, not convenience):

    1. **Strip comments, not string contents.** A naive "strip everything
       quoted" pass mishandles JSX text content like
       `<Button>I won't submit</Button>` — the apostrophe in "won't" is not
       a JavaScript string delimiter, but a strip that treats `'` as a
       string-open swallows the rest of the file. JSX-shape regexes don't
       care about quoted string contents anyway (strings don't contain JSX
       tags), so leaving them in is safe.

    2. **String-aware comment detection.** A `/*` or `//` that appears
       INSIDE a JavaScript string literal (`"a /* b */ c"`,
       `"// not a comment"`) is not a real comment. We track `"`- and
       backtick-delimited strings (with `\\` escape handling) to avoid
       false-positive comment starts inside strings. We do NOT track
       single-quote `'...'` as a string delimiter because JSX text frequently
       contains lone apostrophes; the worst case is a single-quoted JS
       string that contains literal `/*` (very rare in practice and the
       resulting strip would damage the string content but not introduce
       false-positive JSX matches).

    3. **Preserve line structure.** Replace stripped non-newline characters
       with spaces, keep `\\n` intact. Error messages stay on the right line.
    """
    out: list[str] = []
    i = 0
    n = len(text)
    in_string: str | None = None  # current opening quote char, or None

    while i < n:
        ch = text[i]
        nxt = text[i + 1] if i + 1 < n else ""

        if in_string is not None:
            # Inside a JS string literal. Handle escapes and string close.
            if ch == "\\" and i + 1 < n:
                out.append(ch)
                out.append(text[i + 1])
                i += 2
                continue
            if ch == in_string:
                in_string = None
            out.append(ch)
            i += 1
            continue

        # Outside any string: comments take priority.
        if ch == "/" and nxt == "*":
            end = text.find("*/", i + 2)
            end = n if end < 0 else end + 2
            for c in text[i:end]:
                out.append("\n" if c == "\n" else " ")
            i = end
            continue

        if ch == "/" and nxt == "/":
            end = text.find("\n", i + 2)
            if end < 0:
                end = n
            out.append(" " * (end - i))
            i = end
            continue

        # String opens (track `"` and backtick; ignore `'`).
        if ch in ('"', "`"):
            in_string = ch
            out.append(ch)
            i += 1
            continue

        out.append(ch)
        i += 1

    return "".join(out)


def _extract_h2_headings(text: str) -> set[str]:
    return {m.group(0) for m in re.finditer(r"^## .+$", text, re.MULTILINE)}


def _heading_matches_required(headings: set[str], required: set[str]) -> set[str]:
    """VF-FIND-019b: a required heading is satisfied if any actual heading STARTS WITH it
    (allows parenthetical clarifications like `## Identity (Tessa)` to count for `## Identity`).
    Returns the set of *missing* required headings."""
    missing: set[str] = set()
    for req in required:
        if any(h == req or h.startswith(req + " ") or h.startswith(req + ":") for h in headings):
            continue
        missing.add(req)
    return missing
