"""Forbidden ambiguity phrases, numeric claim labels, raw px in layout/components, hedges, cross-subskill cites.

Generated by scripts/_split_validators.py. Do not hand-edit module structure;
update the source and re-run the splitter.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from ._common import (  # noqa: F401  # re-exported helpers are intentional
    CONTRAST_RATIO_PATTERN,
    CROSS_CUT_TERMS,
    FORBIDDEN_AMBIGUITY_PHRASES,
    Findings,
    HEDGE_ON_NUMBER_PATTERN,
    NUMERIC_LABEL_PATTERN,
    _strip_excluded_contexts,
)

def check_forbidden_ambiguity(root: Path, findings: Findings) -> None:
    """The implementation safety contract forbids ambiguous phrases like 'as needed' /
    'modern library' / 'handle edge cases'. Scan authored prose only — skip code blocks,
    blockquotes, and 'What we are NOT doing' sections (which intentionally cite the phrases)."""
    skip_dirs = {"tokens", "auditability", "figma-import-bundle", "retrofit"}
    for path in root.rglob("*.md"):
        rel = path.relative_to(root)
        if any(part in skip_dirs for part in rel.parts):
            continue
        raw = path.read_text(encoding="utf-8")
        stripped = _strip_excluded_contexts(raw)
        lower = stripped.lower()
        for phrase in FORBIDDEN_AMBIGUITY_PHRASES:
            idx = lower.find(phrase)
            while idx >= 0:
                line_no = stripped[:idx].count("\n") + 1
                findings.fail(
                    f"Forbidden ambiguous phrase '{phrase}' in "
                    f"{str(rel).replace(chr(92), '/')}:{line_no} — implementation-safety contract failure."
                )
                idx = lower.find(phrase, idx + 1)


def check_numeric_claim_labels(root: Path, findings: Findings) -> None:
    """VF-FIND-002: numeric claims (contrast ratios, perf budgets, timings) must be paired
    with a (measured|computed|estimated|target|assumption) label within ~80 chars.
    Skip code blocks, blockquotes, and 'What we are NOT doing' sections."""
    skip_dirs = {"tokens", "auditability", "figma-import-bundle", "retrofit"}
    for path in root.rglob("*.md"):
        rel = path.relative_to(root)
        if any(part in skip_dirs for part in rel.parts):
            continue
        raw = path.read_text(encoding="utf-8")
        stripped = _strip_excluded_contexts(raw)
        for m in CONTRAST_RATIO_PATTERN.finditer(stripped):
            ctx_start = max(0, m.start() - 80)
            ctx_end = min(len(stripped), m.end() + 80)
            ctx = stripped[ctx_start:ctx_end]
            if not NUMERIC_LABEL_PATTERN.search(ctx):
                line_no = stripped[: m.start()].count("\n") + 1
                findings.warn(
                    f"Numeric claim '{m.group(0)}' in "
                    f"{str(rel).replace(chr(92), '/')}:{line_no} lacks "
                    f"(measured|computed|estimated|target|assumption) label within 80 chars. "
                    f"Per VF-FIND-002 — numeric precision without computation source."
                )


def check_raw_px_in_layout_and_components(root: Path, findings: Findings) -> None:
    """VF-FIND-006: raw px in layout / component / screen specs corrupts token-tier discipline.
    Layout-system + mobile-and-responsive + component specs + screen specs should reference tokens.
    Raw px is permitted only when paired with a (target) or (measured) label AND a DEC-NNN cite."""
    scan_dirs = ["03-structure", "05-components", "06-screens"]
    raw_px_pattern = re.compile(r"\b(\d+)\s*px\b")
    for sub in scan_dirs:
        sub_dir = root / sub
        if not sub_dir.exists():
            continue
        for path in sub_dir.rglob("*.md"):
            rel = path.relative_to(root)
            raw = path.read_text(encoding="utf-8")
            stripped = _strip_excluded_contexts(raw)
            hits = list(raw_px_pattern.finditer(stripped))
            unlabeled = 0
            for m in hits:
                ctx_start = max(0, m.start() - 80)
                ctx_end = min(len(stripped), m.end() + 80)
                ctx = stripped[ctx_start:ctx_end]
                # OK if either a numeric label or a DEC-NNN cite is nearby.
                if NUMERIC_LABEL_PATTERN.search(ctx):
                    continue
                if re.search(r"\bDEC-\d{3,4}\b", ctx):
                    continue
                # OK if px is part of a breakpoint reference (e.g. "640 px breakpoint").
                if "breakpoint" in ctx.lower() or "min-width" in ctx.lower():
                    continue
                # VF-FIND-012: OK if px is paired with a token reference in either direction,
                # e.g. "size.10 (40px)" or "(40px) — size.10". Use the RAW text (not stripped)
                # because backtick-wrapped tokens like `size.10` get blanked by
                # _strip_excluded_contexts. Positions are stable because the stripper
                # preserves char-for-char length.
                raw_lookback = raw[max(0, m.start() - 40): m.start()]
                raw_lookahead = raw[m.end(): m.end() + 40]
                token_ref = re.compile(r"\b(?:size|icon|radius|space|type)\.[\w-]+\b")
                if token_ref.search(raw_lookback) or token_ref.search(raw_lookahead):
                    continue
                # OK if px is part of a documented constraint like `1px border` or `2px outline`.
                value = int(m.group(1))
                if value <= 2 and re.search(r"\b\d+\s*px\b\s+(border|outline|ring|stroke)", ctx, re.IGNORECASE):
                    continue
                unlabeled += 1
            if unlabeled >= 3:
                findings.warn(
                    f"Raw-px density in {str(rel).replace(chr(92), '/')}: "
                    f"{unlabeled} unlabeled px values found. "
                    f"Per VF-FIND-006 — extend token scale or add (target) + DEC-NNN cite."
                )


def check_hedge_on_known_values(root: Path, findings: Findings) -> None:
    """VF-FIND-008: rhetorical hedges (≥, ~, approximately) on numbers that look like
    exact specifications. False-positive risk; warn-level only."""
    skip_dirs = {"tokens", "auditability", "figma-import-bundle"}
    # Known-exact contexts where a hedge is suspicious.
    suspicious_contexts = re.compile(
        r"\b(nav items?|destinations?|tabs?|columns?|breakpoints?|elevation levels?|"
        r"primary colors?|side rail items?|tier|step|click|tap|second)\b",
        re.IGNORECASE,
    )
    for path in root.rglob("*.md"):
        rel = path.relative_to(root)
        if any(part in skip_dirs for part in rel.parts):
            continue
        raw = path.read_text(encoding="utf-8")
        stripped = _strip_excluded_contexts(raw)
        for m in HEDGE_ON_NUMBER_PATTERN.finditer(stripped):
            ctx_start = max(0, m.start() - 60)
            ctx_end = min(len(stripped), m.end() + 60)
            ctx = stripped[ctx_start:ctx_end]
            if suspicious_contexts.search(ctx):
                line_no = stripped[: m.start()].count("\n") + 1
                findings.warn(
                    f"Possible hedge-on-known-value '{m.group(0)}' near a fixed-count "
                    f"concept in {str(rel).replace(chr(92), '/')}:{line_no}. "
                    f"Per VF-FIND-008 — if the value is exact, state it exactly. "
                    f"Reserve ≥ / ~ / approximately for genuine ranges or estimates."
                )


def check_cross_subskill_cites(root: Path, findings: Findings) -> None:
    """VF-FIND-007: when later subskills describe cross-cut concepts (terms decided
    in earlier subskills), they should cite the relevant DEC-NNN. Heuristic, warn-level."""
    # Subskill order: which directories come "later" and should cite "earlier".
    # 03-structure cites 01-foundations / 02-visual-language
    # 04-interaction cites 01-foundations / 02-visual-language / 03-structure
    # 05-components / 06-screens cite all earlier
    # 07-quality cites everything
    later_dirs = ["03-structure", "04-interaction", "05-components", "06-screens", "07-quality"]
    for sub in later_dirs:
        sub_dir = root / sub
        if not sub_dir.exists():
            continue
        for path in sub_dir.rglob("*.md"):
            rel = path.relative_to(root)
            raw = path.read_text(encoding="utf-8")
            stripped = _strip_excluded_contexts(raw)
            # VF-FIND-013: per-paragraph windowing (paragraphs split by blank lines).
            # A cross-cut term satisfies the cite requirement if the surrounding paragraph
            # contains any DEC-NNN reference. This eliminates 90% of the noise from
            # narratives that cite once at the top of a section and then use the term freely.
            paragraphs = re.split(r"\n\s*\n", stripped)
            # Build offset map for line-number calculation.
            offset = 0
            warned_terms_in_file: set[str] = set()
            for para in paragraphs:
                para_start = offset
                offset += len(para) + 2  # +2 for the \n\n delimiter
                # Skip headings-only paragraphs (the subskill that owns the term).
                if para.lstrip().startswith("#"):
                    continue
                has_cite = re.search(r"\bDEC-\d{3,4}", para)
                for term in CROSS_CUT_TERMS:
                    if term in warned_terms_in_file:
                        continue
                    pattern = re.compile(rf"\b{re.escape(term)}\b", re.IGNORECASE)
                    m = pattern.search(para)
                    if not m:
                        continue
                    if has_cite:
                        continue
                    abs_pos = para_start + m.start()
                    line_no = stripped[: abs_pos].count("\n") + 1
                    findings.warn(
                        f"Cross-cut term '{term}' in {str(rel).replace(chr(92), '/')}:{line_no} "
                        f"without nearby DEC-NNN cite. Per VF-FIND-007 — when describing a "
                        f"concept owned by an earlier subskill, cite the source DEC in the "
                        f"same paragraph."
                    )
                    warned_terms_in_file.add(term)
