"""v1.8.0 color-decision-basis check.

Generated by scripts/_split_validators.py. Do not hand-edit module structure;
update the source and re-run the splitter.
"""
from __future__ import annotations

import re
from pathlib import Path

from ._common import (  # noqa: F401  # re-exported helpers are intentional
    Findings,
)


# Patterns that strongly suggest the file is declaring a palette.
_PALETTE_HEX_PATTERN = re.compile(r"#[0-9a-fA-F]{6}\b")
_PALETTE_OKLCH_PATTERN = re.compile(r"oklch\(", re.IGNORECASE)
_COLOR_REFERENCE_CITE = "color-theory-and-decision-matrix.md"


def check_color_decision_basis(root: Path, findings: Findings) -> None:
    """VF-FIND-047: any subskill doc that declares a color palette (hex or OKLCH
    stops, ramps, contrast tables) must cite `color-theory-and-decision-matrix.md`.

    Rationale: before VF-FIND-047 the agent could pick a palette from a menu of
    options without theory grounding or a decision matrix. Citing the reference
    proves the agent consulted the harmony schemes, meaning table, and
    derivation method.

    Scans:
    - `02-visual-language/design-tokens.md` — main palette declaration site.
    - `02-visual-language/brand-identity.md` — color philosophy.
    - `02-visual-language/surface-treatments.md` — gradient declarations.

    Warns when the file contains palette-shape evidence (hex/OKLCH stops) but
    does NOT cite the color reference.
    """
    palette_files = [
        ("design-tokens.md", root / "02-visual-language" / "design-tokens.md"),
        ("brand-identity.md", root / "02-visual-language" / "brand-identity.md"),
        ("surface-treatments.md", root / "02-visual-language" / "surface-treatments.md"),
    ]
    for name, path in palette_files:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        has_palette = bool(
            _PALETTE_HEX_PATTERN.search(text)
            or _PALETTE_OKLCH_PATTERN.search(text)
        )
        if not has_palette:
            continue
        if _COLOR_REFERENCE_CITE not in text:
            findings.warn(
                f"VF-FIND-047: {name} declares a color palette (hex or OKLCH stops "
                f"detected) but does not cite `color-theory-and-decision-matrix.md`. "
                f"Palette decisions require theory + matrix grounding — see the "
                f"reference for harmony schemes, meaning table, derivation method, "
                f"and color-blindness verification."
            )
