"""DEC-ID shape, decision-log integrity, cross-tree dupes, ID resolution, per-DEC metadata, persona-DEC consistency, range allocation.

Generated by scripts/_split_validators.py. Do not hand-edit module structure;
update the source and re-run the splitter.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from ._common import (  # noqa: F401  # re-exported helpers are intentional
    DEC_HEADING_PATTERN,
    Findings,
    SKILL_DEC_CROSS_REFS,
    STRICT_DEC_BAD,
    STRICT_DEC_SUBDEC,
    SUBSKILL_DEC_RANGES,
)

def check_strict_dec_shape(root: Path, findings: Findings) -> None:
    """VF-FIND-005: every DEC-ID must match canonical shape ^DEC-\\d{3,4}(\\.\\d+)?$.
    Workaround suffixes like _icon, -tmp, or Specforge-style DEC-CATEGORY-NNN are flagged."""
    # `auditability/` is excluded because the run-log records historical events that may
    # reference now-deprecated malformed IDs verbatim. Cleanup tracking files (debt registry,
    # plugin findings) likewise document malformed IDs intentionally.
    skip_dirs = {"figma-import-bundle", "auditability"}
    skip_files_basenames = {"phase-1-3-debt.md", "PLUGIN-FINDINGS.md"}
    # Specforge-style IDs that legitimately appear when cross-referencing app-plan.
    specforge_cross_cite = re.compile(r"\bapp-plan/DEC-[A-Z]+-\d+\b")
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix not in {".md", ".json"}:
            continue
        rel = path.relative_to(root)
        if any(part in skip_dirs for part in rel.parts):
            continue
        if path.name in skip_files_basenames:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        # Strip legitimate Specforge cross-cites before scanning.
        scan_text = specforge_cross_cite.sub("", text)
        # VF-FIND-011 part 2 / cleanup: also strip Specforge-style IDs that are explicitly
        # contextualized as Specforge references (the word "Specforge" within 60 chars).
        # This prevents false-positives on `(Specforge DEC-SMS-001)` and
        # `Specforge-derived (DEC-SCOPE-001, DEC-NONGOAL-001, ...)` lists.
        def _strip_specforge_contextualized(t: str) -> str:
            # First find any Specforge-style ID
            out_parts: list[str] = []
            cursor = 0
            for mm in re.finditer(r"\bDEC-[A-Z][A-Z0-9-]*-\d+\b", t):
                window_start = max(0, mm.start() - 60)
                window_end = min(len(t), mm.end() + 60)
                window = t[window_start:window_end]
                if "Specforge" in window or "app-plan" in window:
                    out_parts.append(t[cursor:mm.start()])
                    cursor = mm.end()
            out_parts.append(t[cursor:])
            return "".join(out_parts)
        scan_text = _strip_specforge_contextualized(scan_text)
        for m in STRICT_DEC_BAD.finditer(scan_text):
            # Permit DEC-NNN.M sub-decision shape.
            if STRICT_DEC_SUBDEC.fullmatch(m.group(0)):
                continue
            line_no = scan_text[: m.start()].count("\n") + 1
            findings.fail(
                f"Malformed DEC-ID '{m.group(0)}' in "
                f"{str(rel).replace(chr(92), '/')}:{line_no} — "
                f"workaround suffixes (_icon, -tmp) and Specforge-style DEC-CATEGORY-NNN "
                f"are forbidden in VisualForge artifacts. Use canonical DEC-NNN or DEC-NNN.M."
            )


def check_decision_log(root: Path, findings: Findings) -> None:
    log = root / "auditability" / "decision-log.md"
    if not log.exists():
        return
    text = log.read_text(encoding="utf-8")
    entries = DEC_HEADING_PATTERN.findall(text)
    if not entries:
        findings.warn("decision-log.md has no DEC-NNN entries found (regex check).")
        return

    # Duplicate-ID detection across the decision log. VF-FIND-011: capture .M sub-decision suffix.
    heading_ids: list[str] = []
    heading_id_pattern = re.compile(r"^###?\s+\[?DEC-(\d{3,4}(?:\.\d+)?)\]?", re.MULTILINE)
    for match in heading_id_pattern.finditer(text):
        heading_ids.append(match.group(1))
    seen: dict[str, int] = {}
    for hid in heading_ids:
        seen[hid] = seen.get(hid, 0) + 1
    duplicates = sorted([hid for hid, n in seen.items() if n > 1])
    for dup in duplicates:
        findings.fail(
            f"Duplicate decision ID: DEC-{dup} appears {seen[dup]} times in decision-log.md. "
            f"Decision IDs must be unique."
        )

    # VF-FIND-001 part B + VF-FIND-011 (sub-decision support): cross-tree duplicate-ID detection.
    # The full match (including .M sub-decision suffix) is the dedupe key so DEC-228 and
    # DEC-228.1 are treated as distinct.
    per_doc_ids: dict[str, list[str]] = {}
    skip_dirs = {"figma-import-bundle", "auditability"}
    heading_pattern_tree = re.compile(r"^###\s+\[?DEC-(\d{3,4}(?:\.\d+)?)\]?", re.MULTILINE)
    for md in root.rglob("*.md"):
        rel = md.relative_to(root)
        if any(part in skip_dirs for part in rel.parts):
            continue
        try:
            content = md.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for m in heading_pattern_tree.finditer(content):
            per_doc_ids.setdefault(m.group(1), []).append(str(rel).replace("\\", "/"))
    for hid, files in per_doc_ids.items():
        if len(files) > 1:
            findings.fail(
                f"Cross-tree duplicate DEC-{hid}: defined as `### DEC-{hid}` headline in "
                f"multiple files: {files}. Each DEC ID must have one source-of-truth heading."
            )

    # Sanity: detect IDs likely outside allocated ranges.
    for hid in heading_ids:
        if len(hid) > 4 or int(hid) > 9999:
            findings.warn(f"DEC-{hid} has unusual ID width; verify against decision-id-allocation.md.")


def check_decision_id_resolution(root: Path, findings: Findings) -> None:
    """VF-FIND-010 part 1: every DEC-NNN reference must resolve to a defined heading,
    unless annotated (Phase N) / (forward-ref) / (capability-pending)."""
    import re as _re

    heading_re = _re.compile(r"^###\s+\[?DEC-(\d{3,4})\]?", _re.MULTILINE)
    cite_re = _re.compile(r"DEC-(\d{3,4})")
    annotation_window = 80  # chars after the DEC-NNN cite

    skip_dirs = {"figma-import-bundle", "auditability"}
    # Forward-ref index files document open cites by design — exempt from resolution check.
    skip_basenames_for_dangling = {"WHATS-MISSING.md", "phase-1-3-debt.md", "PLUGIN-FINDINGS.md"}
    defined: set[str] = set()
    for md in root.rglob("*.md"):
        rel = md.relative_to(root)
        if any(part in skip_dirs for part in rel.parts):
            continue
        text = md.read_text(encoding="utf-8")
        for m in heading_re.finditer(text):
            defined.add(m.group(1))

    # Strip fenced code blocks from cite-resolution input — example snippets in code
    # blocks should not be treated as live cross-cites.
    fenced_code = _re.compile(r"```[\s\S]*?```")
    dangling: dict[str, list[str]] = {}
    for md in root.rglob("*.md"):
        rel = md.relative_to(root)
        if any(part in skip_dirs for part in rel.parts):
            continue
        if md.name in skip_basenames_for_dangling:
            continue
        raw_text = md.read_text(encoding="utf-8")
        text = fenced_code.sub(lambda m: " " * len(m.group(0)), raw_text)
        for m in cite_re.finditer(text):
            dec = m.group(1)
            if dec in defined:
                continue
            # Look at the next annotation_window chars for a forward-ref escape.
            tail = text[m.end(): m.end() + annotation_window]
            if any(tok in tail for tok in ("(Phase", "forward-ref", "capability-pending", "Specforge", "(external")):
                continue
            # Also accept the same tokens immediately before the cite (within 40 chars).
            head = text[max(0, m.start() - 40): m.start()]
            if any(tok in head for tok in ("(Phase", "forward-ref", "capability-pending", "Specforge", "(external")):
                continue
            dangling.setdefault(dec, []).append(str(rel).replace("\\", "/"))

    for dec, files in sorted(dangling.items()):
        unique_files = sorted(set(files))
        findings.fail(
            f"Dangling cross-cite DEC-{dec}: cited in {unique_files} but no `### DEC-{dec}` "
            f"heading exists anywhere in the doc tree. Either define it, or annotate the "
            f"reference as `(Phase N)`, `(forward-ref)`, or `(capability-pending)`."
        )


def check_decision_id_singleton(root: Path, findings: Findings) -> None:
    """VF-FIND-010 part 2 + VF-FIND-014: flag DEC-IDs cited with two distinct parenthetical
    themes (heuristic for ID overload). Annotator tokens (Specforge, forward-ref, etc.) are
    stripped so they don't count as themes."""
    import re as _re

    cite_with_paren = _re.compile(r"DEC-(\d{3,4})\s*\(([^)]{3,80})\)")
    skip_dirs = {"figma-import-bundle", "auditability"}
    # VF-FIND-014: annotation-only parens to skip entirely.
    annotation_only = {
        "specforge", "forward-ref", "capability-pending", "phase 5", "phase 6",
        "phase 1 cleanup", "phase 4 batch 2", "external",
    }
    themes: dict[str, set[str]] = {}
    for md in root.rglob("*.md"):
        rel = md.relative_to(root)
        if any(part in skip_dirs for part in rel.parts):
            continue
        text = md.read_text(encoding="utf-8")
        for m in cite_with_paren.finditer(text):
            dec = m.group(1)
            theme_raw = m.group(2).strip().lower()
            # Strip trailing phase / forward-ref annotations within a theme
            for tok in ("— forward-ref", "forward-ref", "phase 5", "phase 6", "capability-pending"):
                theme_raw = theme_raw.replace(tok, "").strip(" —-,")
            # VF-FIND-014: if the paren is annotation-only, skip entirely
            if theme_raw in annotation_only:
                continue
            # Also skip if it's just a Specforge marker with no real theme
            if theme_raw.startswith("specforge") and len(theme_raw) < 20:
                continue
            theme_key = theme_raw[:40]
            if not theme_key:
                continue
            themes.setdefault(dec, set()).add(theme_key)

    # VF-FIND-020: theme normalization. Strip generic-list markers ("personas", "binding",
    # "composition") and lemmatize plural→singular so "personas"/"persona" collapse.
    generic_themes = {
        "personas", "persona", "binding", "composition", "list", "group", "set",
        "ref", "reference", "cite", "see frontmatter", "see file-level cross-cites in frontmatter",
        "this file", "this file — conformance target",
    }
    def _normalize_theme(t: str) -> str:
        t = t.strip()
        if t in generic_themes:
            return ""
        # Strip trailing parentheticals like "(composition)" etc.
        t = _re.sub(r"\s*\([^)]+\)\s*$", "", t).strip()
        # Singularize trailing 's' when it's a plain noun-like word
        if len(t) > 3 and t.endswith("s") and not t.endswith("ss"):
            t = t[:-1]
        return t

    for dec, theme_set in sorted(themes.items()):
        # Normalize each theme + drop empties (generic markers).
        normalized = {_normalize_theme(t) for t in theme_set}
        normalized.discard("")
        if len(normalized) > 1:
            # Heuristic: split on shared root tokens. If two themes share no word, warn.
            tokens_list = [set(t.split()) for t in normalized]
            overlap = set.intersection(*tokens_list) if tokens_list else set()
            if not overlap:
                findings.warn(
                    f"DEC-{dec} cited with disjoint parenthetical themes: {sorted(normalized)}. "
                    f"Possible ID overload — verify all cites refer to the same decision."
                )


def check_per_dec_metadata(root: Path, findings: Findings) -> None:
    """VF-FIND-010 part 3 + VF-FIND-019 (typo near-miss): every `### DEC-NNN` heading must
    be followed within 8 lines by Cross-cites consumed / Confidence / Reversal trigger
    metadata. Common typos (Reversal thrigger, Cross cites consumed, Confidnece, etc.)
    are flagged separately as BLOCK-level so they don't pass the substring check by accident."""
    import re as _re

    heading_re = _re.compile(r"^###\s+\[?DEC-(\d{3,4}(?:\.\d+)?)\]?", _re.MULTILINE)
    required = ("Cross-cites consumed", "Confidence", "Reversal trigger")
    # VF-FIND-019: known typo variants of the required field labels. Detecting these
    # in the metadata window indicates a content bug (the author tried to add the field
    # but misspelled it; substring check below would still report it as missing).
    typo_variants = {
        "Cross-cites consumed": ["Cross cites consumed", "Cross-sites consumed", "Crosscites consumed", "Cross-cites consummed"],
        "Confidence": ["Confidnece", "Confidance", "Confidnce"],
        "Reversal trigger": ["Reversal thrigger", "Reverasl trigger", "Reversal triger", "Reversal-trigger"],
    }
    skip_dirs = {"figma-import-bundle", "auditability"}
    window_lines = 8

    for md in root.rglob("*.md"):
        rel = md.relative_to(root)
        if any(part in skip_dirs for part in rel.parts):
            continue
        text = md.read_text(encoding="utf-8")
        lines = text.split("\n")
        for i, line in enumerate(lines):
            m = _re.match(r"^###\s+\[?DEC-(\d{3,4}(?:\.\d+)?)\]?", line)
            if not m:
                continue
            window = "\n".join(lines[i: i + window_lines + 1])
            missing = [tok for tok in required if tok not in window]
            if missing:
                findings.warn(
                    f"{rel}: DEC-{m.group(1)} is missing per-DEC metadata "
                    f"({', '.join(missing)}) within {window_lines} lines of the heading. "
                    f"File-end summary rolls do not satisfy this requirement."
                )
            # VF-FIND-019: typo near-miss detection
            for canonical, typos in typo_variants.items():
                for typo in typos:
                    if typo in window:
                        findings.fail(
                            f"{rel}: DEC-{m.group(1)} per-DEC metadata typo near-miss — "
                            f"found `{typo}` (likely intended `{canonical}`). "
                            f"Fix typo so the field is recognized."
                        )


def check_persona_dec_consistency(root: Path, findings: Findings) -> None:
    """VF-FIND-015: persona DEC-IDs are owned by specific persona files; cites that
    parenthetically describe a persona DEC with a different persona's name are misattributions.

    Builds an authoritative map from `01-foundations/personas/*.md` by reading each persona
    file's top heading and `### DEC-NNN` entry. Then scans all VF artifacts for cites of
    those DEC-IDs and flags any that mention a different persona name in the parenthetical.
    """
    import re as _re

    personas_dir = root / "01-foundations" / "personas"
    if not personas_dir.exists():
        return

    # Build persona-name → DEC-ID map from filename + heading.
    # Filenames follow convention: persona-NAME-..., anti-persona-NAME-..., edge-case-NAME-..., pair-NAME1-and-NAME2-...
    persona_decs: dict[str, str] = {}  # name (lower) -> DEC-NNN
    dec_to_personas: dict[str, set[str]] = {}  # DEC-NNN -> set of names (lower)

    name_pattern = _re.compile(r"^(?:persona|anti-persona|edge-case|pair)-(.+?)\.md$")
    dec_heading = _re.compile(r"^###\s+\[?DEC-(\d{3,4})\]?", _re.MULTILINE)

    for path in personas_dir.glob("*.md"):
        m = name_pattern.match(path.name)
        if not m:
            continue
        slug = m.group(1)
        # Extract just the persona names from the slug (strip role descriptors)
        # Examples: amara-bookkeeper -> amara; tessa-tax-advisor -> tessa; quentin-returning -> quentin;
        #           amara-and-smb-owner -> [amara, smb-owner]
        if "-and-" in slug:
            names = slug.split("-and-")
            names = [n.split("-")[0] for n in names]
        else:
            names = [slug.split("-")[0]]
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        dec_matches = dec_heading.findall(text)
        if not dec_matches:
            continue
        dec_id = dec_matches[0]
        for name in names:
            persona_decs[name.lower()] = dec_id
            dec_to_personas.setdefault(dec_id, set()).add(name.lower())

    if not dec_to_personas:
        return

    # Now scan for misattributions: cites like DEC-029 (Tessa anti-persona) when DEC-029 is Quentin's.
    all_persona_names: set[str] = set(persona_decs.keys())
    cite_with_paren = _re.compile(r"DEC-(\d{3,4})\s*\(([^)]{3,120})\)")
    skip_dirs = {"figma-import-bundle", "auditability", "01-foundations/personas"}

    # VF-FIND-017: also scan the surrounding ±300 char window for persona-name density.
    # A cite of DEC-NNN (any-theme) where the surrounding paragraph mentions persona X ≥2
    # times but X is NOT in owners → warn-level finding.
    window_size = 300
    name_mention_threshold = 2

    for md in root.rglob("*.md"):
        rel = md.relative_to(root)
        rel_str = str(rel).replace("\\", "/")
        if any(part in {"figma-import-bundle", "auditability"} for part in rel.parts):
            continue
        if rel_str.startswith("01-foundations/personas/"):
            continue
        try:
            text = md.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        text_lower = text.lower()
        for m in cite_with_paren.finditer(text):
            dec = m.group(1)
            theme = m.group(2).lower()
            if dec not in dec_to_personas:
                continue
            owners = dec_to_personas[dec]
            # Paren-scope check (original VF-FIND-015 behavior, BLOCK-level).
            mentioned = {name for name in all_persona_names if _re.search(rf"\b{_re.escape(name)}\b", theme)}
            wrong = mentioned - owners
            if wrong:
                line_no = text[: m.start()].count("\n") + 1
                findings.fail(
                    f"Persona-DEC misattribution in {rel_str}:{line_no}: "
                    f"`DEC-{dec} ({m.group(2)})` cites persona(s) {sorted(wrong)} but "
                    f"DEC-{dec} is owned by {sorted(owners)}. Fix the cite or the parenthetical."
                )
                continue
            # VF-FIND-017: context-scope check (WARN-level).
            ctx_start = max(0, m.start() - window_size)
            ctx_end = min(len(text), m.end() + window_size)
            ctx = text_lower[ctx_start:ctx_end]
            # Skip if any owner name appears in context — the cite is consistent with its surroundings.
            if any(_re.search(rf"\b{_re.escape(o)}\b", ctx) for o in owners):
                continue
            # Count mentions of each non-owner persona in the window.
            for name in all_persona_names:
                if name in owners:
                    continue
                count = len(_re.findall(rf"\b{_re.escape(name)}\b", ctx))
                if count >= name_mention_threshold:
                    line_no = text[: m.start()].count("\n") + 1
                    findings.warn(
                        f"Persona-DEC context drift in {rel_str}:{line_no}: "
                        f"`DEC-{dec}` cited but surrounding ±{window_size} chars mention "
                        f"persona '{name}' {count} times. DEC-{dec} is owned by {sorted(owners)}. "
                        f"Verify the cite belongs to this paragraph's persona."
                    )
                    break


def check_dec_range_allocation(root: Path, findings: Findings) -> None:
    """VF-FIND-042: every DEC mentioned in a subskill SKILL.md must be either
    within that subskill's allocated range (per `decision-id-allocation.md`) OR
    a documented cross-reference to another subskill's range.

    Out-of-range DECs corrupt the cross-tree allocation discipline and risk
    collision with other subskills' decisions — the exact bug VF-FIND-001 and
    VF-FIND-005 hardened the plugin against, applied to SKILL.md prose examples
    rather than to decision-log entries.

    Scope: this check operates on the **plugin source tree**, not on a generated
    `docs/design-system/` corpus. It walks `<plugin_root>/skills/*/SKILL.md`.
    Skipped when run against a generated design-system root (no `SKILL.md` files
    will be found there, so the check is a no-op for those invocations).
    """
    # Resolve plugin root from the validator script's own location.
    plugin_root = Path(__file__).resolve().parent.parent
    skills_dir = plugin_root / "skills"
    if not skills_dir.exists():
        return

    inline_re = re.compile(r"DEC-(\d{3,4})")
    for skill_dir in sorted(skills_dir.iterdir()):
        if not skill_dir.is_dir():
            continue
        if skill_dir.name.startswith("_"):
            continue
        if skill_dir.name == "visualforge":
            continue  # orchestrator owns no DEC range
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            continue
        rng = SUBSKILL_DEC_RANGES.get(skill_dir.name)
        if not rng:
            findings.warn(
                f"VF-FIND-042: {skill_dir.name} has no entry in SUBSKILL_DEC_RANGES; "
                f"unable to verify DEC allocation. Add it to validate_design_docs.py."
            )
            continue
        lo, hi = rng
        cross_refs = SKILL_DEC_CROSS_REFS.get(skill_dir.name, {})
        text = skill_md.read_text(encoding="utf-8")
        decs = set(int(m.group(1)) for m in inline_re.finditer(text))
        out_of_range = sorted(
            d for d in decs if not (lo <= d <= hi) and d not in cross_refs
        )
        if out_of_range:
            findings.warn(
                f"VF-FIND-042: {skill_dir.name}/SKILL.md mentions DECs outside its "
                f"allocated range ({lo}-{hi}): {out_of_range}. Either renumber within "
                f"the range OR add to SKILL_DEC_CROSS_REFS if they reference another "
                f"subskill's DEC."
            )
