"""Regression fixture self-test harness.

Generated by scripts/_split_validators.py. Do not hand-edit module structure;
update the source and re-run the splitter.
"""
from __future__ import annotations

import json
import re
import sys
import shutil
import tempfile
from pathlib import Path

from ._common import (  # noqa: F401  # re-exported helpers are intentional
    Findings,
)


def _run_self_test() -> int:
    """VF-FIND-022: regression fixture harness.

    Discovers `examples/fixtures/*/` directories (excluding `_base`), merges each
    fixture over the base corpus into a tmp dir, runs the validator, compares
    actual findings against the fixture's expected.json. Reports per-fixture
    verdict; overall exit non-zero on any mismatch.
    """
    # Import run lists lazily to avoid circular import with __init__.py
    from . import run_mid_run_checks, run_full_checks

    _json = json

    # __file__ is now scripts/validators/harness.py, so plugin root is 3 levels up.
    plugin_root = Path(__file__).resolve().parent.parent.parent
    fixtures_root = plugin_root / "examples" / "fixtures"
    base_dir = fixtures_root / "_base"
    if not fixtures_root.exists() or not base_dir.exists():
        print(f"FAIL: fixtures dir not found at {fixtures_root}", file=sys.stderr)
        return 2

    fixtures = sorted(p for p in fixtures_root.iterdir() if p.is_dir() and p.name != "_base")
    if not fixtures:
        print("FAIL: no fixtures found", file=sys.stderr)
        return 2

    results: list[tuple[str, bool, list[str]]] = []
    for fx in fixtures:
        expected_path = fx / "expected.json"
        if not expected_path.exists():
            results.append((fx.name, False, [f"missing expected.json"]))
            continue
        try:
            expected = _json.loads(expected_path.read_text(encoding="utf-8"))
        except Exception as e:
            results.append((fx.name, False, [f"invalid expected.json: {e}"]))
            continue

        with tempfile.TemporaryDirectory() as tmp:
            staging = Path(tmp) / "design-system"
            # Copy base, then overlay fixture (excluding expected.json).
            shutil.copytree(base_dir, staging)
            for src in fx.rglob("*"):
                if src.name == "expected.json":
                    continue
                if not src.is_file():
                    continue
                rel = src.relative_to(fx)
                dst = staging / rel
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)

            findings = Findings()
            mode = expected.get("mode", "mid-run")
            if mode == "mid-run":
                run_mid_run_checks(staging, findings)
            else:
                run_full_checks(staging, findings, strict=False)

            issues: list[str] = []
            for needle in expected.get("errors_include", []):
                if not any(needle in e for e in findings.errors):
                    issues.append(f"errors_include missing: {needle!r}")
            for needle in expected.get("errors_exclude", []):
                if any(needle in e for e in findings.errors):
                    issues.append(f"errors_exclude triggered: {needle!r}")
            for needle in expected.get("warnings_include", []):
                if not any(needle in w for w in findings.warnings):
                    issues.append(f"warnings_include missing: {needle!r}")
            for needle in expected.get("warnings_exclude", []):
                if any(needle in w for w in findings.warnings):
                    issues.append(f"warnings_exclude triggered: {needle!r}")
            # Verdict assertion — required for positive-control fixtures. Ensures the
            # validator actually ran, vs. silently being a no-op.
            verdict_must_be = expected.get("verdict_must_be")
            if verdict_must_be is not None:
                actual_verdict = "PASS" if findings.ok else "FAIL"
                if actual_verdict != verdict_must_be:
                    issues.append(
                        f"verdict_must_be mismatch: expected {verdict_must_be}, got "
                        f"{actual_verdict} ({len(findings.errors)} errors)"
                    )
            # Liveness assertion — proves the validator did SOMETHING (emitted at least
            # one finding from the base corpus). Use sparingly; fixtures that legitimately
            # produce a clean PASS won't satisfy this.
            min_total = expected.get("min_total_findings")
            if min_total is not None:
                actual_total = len(findings.errors) + len(findings.warnings)
                if actual_total < min_total:
                    issues.append(
                        f"min_total_findings: expected >= {min_total}, got {actual_total}"
                    )

            results.append((fx.name, len(issues) == 0, issues))

    passed = sum(1 for _, ok, _ in results if ok)
    total = len(results)
    print(f"--- Self-test results ({passed}/{total} passed) ---")
    for name, ok, issues in results:
        status = "PASS" if ok else "FAIL"
        print(f"  [{status}] {name}")
        for issue in issues:
            print(f"      - {issue}")
    return 0 if passed == total else 1
