"""v1.8.0 plugin-source contract walker: ensures SKILL.md files cite required shared references and contain required subsections.

Generated by scripts/_split_validators.py. Do not hand-edit module structure;
update the source and re-run the splitter.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from ._common import (  # noqa: F401  # re-exported helpers are intentional
    Findings,
)

def check_plugin_source_contracts(root: Path, findings: Findings) -> None:
    """VF-FIND-044 follow-up: walk plugin source `skills/*/SKILL.md` and assert
    that each subskill's global-quality-rules section cites the shared references
    it depends on. Catches the class of bug VF-FIND-041 surfaced when v1.8.0
    forgot to wire iconography and content-design into the new shared references.

    Scope: plugin source tree, not generated docs (mirrors `check_dec_range_allocation`).
    """
    plugin_root = Path(__file__).resolve().parent.parent
    skills_dir = plugin_root / "skills"
    if not skills_dir.exists():
        return

    # subskill -> list of shared references that must appear in its SKILL.md
    REQUIRED_CITES = {
        # Visual subskills must cite visual-default-breakers.
        "visualforge-brand-identity":        ["visual-default-breakers.md"],
        "visualforge-layout-system":         ["visual-default-breakers.md"],
        "visualforge-surface-treatments":    ["visual-default-breakers.md"],
        "visualforge-imagery-illustration":  ["visual-default-breakers.md"],
        "visualforge-iconography":           ["visual-default-breakers.md"],
        "visualforge-mobile-and-responsive": ["visual-default-breakers.md"],
        # State-page subskills must cite state-page-patterns.
        "visualforge-auth-flows":                  ["state-page-patterns.md"],
        "visualforge-system-pages":                ["state-page-patterns.md"],
        "visualforge-notifications-and-lifecycle": ["state-page-patterns.md"],
        # Content-design is owner of multiple shared-pattern bits.
        "visualforge-content-design": ["state-page-patterns.md", "visual-default-breakers.md"],
        # Timing-token consumers must cite motion-design as source of truth.
        "visualforge-micro-interactions":  ["visualforge-motion-design"],
        "visualforge-scroll-and-gesture":  ["visualforge-motion-design"],
    }

    # Subskills whose SKILL.md must contain a specific contract subsection (template).
    # Subsection titles must match the actual SKILL.md heading (or a variant).
    # Provided as a list of acceptable substrings — any one match satisfies.
    REQUIRED_SUBSECTIONS = {
        "visualforge-component-system": [
            ["React-implementation contract"],  # per VF-FIND-036 §17d
        ],
        "visualforge-frontend-contract": [
            ["React / framework quality discipline", "React quality discipline"],  # §17, per VF-FIND-036
        ],
    }

    for skill_name, refs in REQUIRED_CITES.items():
        skill_md = skills_dir / skill_name / "SKILL.md"
        if not skill_md.exists():
            continue
        text = skill_md.read_text(encoding="utf-8")
        for ref in refs:
            if ref not in text:
                findings.warn(
                    f"VF-FIND-044: {skill_name}/SKILL.md does not cite required "
                    f"shared reference `{ref}`. Per the plugin-source contract walker, "
                    f"this subskill must reference it in its global quality rules."
                )

    for skill_name, section_alternatives_list in REQUIRED_SUBSECTIONS.items():
        skill_md = skills_dir / skill_name / "SKILL.md"
        if not skill_md.exists():
            continue
        text = skill_md.read_text(encoding="utf-8")
        for alternatives in section_alternatives_list:
            if not any(alt in text for alt in alternatives):
                findings.warn(
                    f"VF-FIND-044: {skill_name}/SKILL.md missing required subsection "
                    f"(any of {alternatives}). The template that produces generated docs "
                    f"depends on it; without it, downstream specs lack required fields."
                )
