"""Implementation mutation log, wrapper-encapsulated semantic drift (h1 -> h3, button-type, etc.).

Generated by scripts/_split_validators.py. Do not hand-edit module structure;
update the source and re-run the splitter.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from ._common import (  # noqa: F401  # re-exported helpers are intentional
    Findings,
    _strip_jsx_comments,
)

def check_implementation_mutation_log(root: Path, findings: Findings) -> None:
    """VF-FIND-024: when implementation has shipped (a sibling `src/components/ui/`
    directory exists at the project root), require an
    `auditability/implementation-mutation-log.md` that records mutation-test
    evidence per component. Per the test-discipline-and-mutation-protocol.

    Heuristic project layout: `<project>/docs/design-system/` is `root`; the
    project root is `root.parent.parent`. Look for `src/components/ui/` there.
    """
    project_root = root.parent.parent if root.parent.name == "docs" else root.parent
    sibling_components = project_root / "src" / "components" / "ui"
    in_tree_components = root / "src" / "components" / "ui"  # fixture-friendly fallback
    components_dir = (
        sibling_components if sibling_components.exists() else in_tree_components
    )
    log_path = root / "auditability" / "implementation-mutation-log.md"

    if not components_dir.exists():
        return

    if not log_path.exists():
        findings.warn(
            f"Implementation directory exists at {components_dir} but "
            f"`auditability/implementation-mutation-log.md` is missing. Per "
            f"`_visualforge-shared/references/test-discipline-and-mutation-protocol.md`, "
            f"every component that ships must have a mutation-test entry."
        )
        return

    log_text = log_path.read_text(encoding="utf-8")
    # For each component spec under 05-components/**, expect a heading referencing it.
    spec_dirs = ["primitives", "composites", "patterns", "domain"]
    missing_entries: list[str] = []
    for sd in spec_dirs:
        d = root / "05-components" / sd
        if not d.exists():
            continue
        for spec in d.glob("*.md"):
            stem = spec.stem
            if stem.startswith("_"):
                continue
            # Heuristic: log mentions the component name as a header or list item.
            # Tolerate dec-id reference OR component-name reference.
            if stem not in log_text and stem.lower() not in log_text.lower():
                missing_entries.append(f"{sd}/{stem}")
    if missing_entries:
        findings.warn(
            f"Implementation mutation log missing entries for shipped components: "
            f"{sorted(missing_entries)[:8]}{'…' if len(missing_entries) > 8 else ''}. "
            f"Each component spec must have a mutation table in "
            f"auditability/implementation-mutation-log.md."
        )


def check_wrapper_semantic_drift(root: Path, findings: Findings) -> None:
    """VF-FIND-025: detect page files that use semantic-wrapper components
    (CardTitle, Alert, etc.) without a disambiguating prop, AND lack an
    alternative source for the semantic in the same file. Catches the
    "h1 → h3 silent regression" class of bug from the sign-in migration.

    Patterns checked, in pairs (wrapper used / required override missing):
      - `<CardTitle` without `as=` AND no raw `<h1` in file → likely h1 regression
      - `<Button type="submit"` inside `<form action={...}>` is required;
        a `<form action={...}>` with a bare `<Button>` (no `type=`) is suspicious
      - `<Alert severity="danger">` is fine; bare `<Alert>` for an error context
        is suspicious — caller may rely on default `severity='info'` for what
        should be a danger condition.

    Heuristic: this check produces WARNs only. False-positives are possible
    (a page may legitimately have no h1 because it's nested under a layout
    that owns the page-primary heading). The warning is a prompt for review,
    not a hard FAIL.

    Comments are stripped before regex matching (see `_strip_jsx_comments`)
    so docstrings describing the pre-migration JSX do not falsely satisfy
    "has_raw_h1" checks.
    """
    import re as _re

    project_root = root.parent.parent if root.parent.name == "docs" else root.parent
    app_dir = project_root / "app"
    if not app_dir.exists():
        # Fixture-friendly fallback.
        app_dir = root / "app"
        if not app_dir.exists():
            return

    for page in app_dir.rglob("page.tsx"):
        try:
            raw_text = page.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        text = _strip_jsx_comments(raw_text)
        rel = page.relative_to(project_root) if page.is_relative_to(project_root) else page

        # Check 1: CardTitle without `as` AND no raw h1 in file.
        if "<CardTitle" in text:
            uses_as = _re.search(r"<CardTitle[^>]+\bas=", text)
            has_raw_h1 = _re.search(r"<h1[\s>]", text)
            if not uses_as and not has_raw_h1:
                findings.warn(
                    f"{rel}: uses <CardTitle> without `as` prop AND no raw <h1> in file. "
                    f"Likely heading-hierarchy regression (CardTitle defaults to <h3>). "
                    f"Per VF-FIND-025 / wrapper-encapsulated semantic drift: page-primary "
                    f"headings must use `<CardTitle as=\"h1\">` or a raw <h1>."
                )

        # Check 2: Button inside form-action without type="submit".
        # Heuristic: find each `<form action=...>` block and check Buttons inside.
        form_blocks = _re.findall(
            r"<form[^>]*\baction=\{[^}]+\}[^>]*>(.*?)</form>",
            text,
            _re.DOTALL,
        )
        for block in form_blocks:
            buttons = _re.findall(r"<Button[^>]*>", block)
            for btn in buttons:
                if "type=" not in btn:
                    findings.warn(
                        f"{rel}: <Button> inside form-action block has no explicit "
                        f"`type=` attribute. VF Button defaults to `type='button'` "
                        f"which will NOT submit the form. Add `type='submit'`. "
                        f"Per VF-FIND-025 wrapper-encapsulated semantic drift."
                    )
                    break  # one warn per form is enough
