"""Slop-word scanner across docs.

Generated by scripts/_split_validators.py. Do not hand-edit module structure;
update the source and re-run the splitter.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from ._common import (  # noqa: F401  # re-exported helpers are intentional
    Findings,
    SLOP_WORDS,
)

def scan_slop(root: Path, findings: Findings, strict: bool) -> None:
    # Scan every markdown file under the design-system tree, except token files and auditability,
    # which carry research notes that legitimately include some surrounding flagged words.
    skip_dirs = {"tokens", "auditability", "figma-import-bundle", "retrofit"}
    for path in root.rglob("*.md"):
        rel = path.relative_to(root)
        if any(part in skip_dirs for part in rel.parts):
            continue
        text = path.read_text(encoding="utf-8")
        doc_rel = str(rel).replace("\\", "/")
        for word in SLOP_WORDS:
            pattern = re.compile(rf"\b{re.escape(word)}\b", re.IGNORECASE)
            for m in pattern.finditer(text):
                ctx_start = max(0, m.start() - 80)
                ctx_end = min(len(text), m.end() + 80)
                context = text[ctx_start:ctx_end].replace("\n", " ")
                line_no = text[: m.start()].count("\n") + 1
                msg = (
                    f"Slop-candidate '{word}' in {doc_rel}:{line_no} — "
                    f"verify concrete behavior nearby. Context: …{context}…"
                )
                if strict:
                    findings.fail(msg)
                else:
                    findings.warn(msg)
