"""v1.8.0 state-page-patterns cross-cite check.

Generated by scripts/_split_validators.py. Do not hand-edit module structure;
update the source and re-run the splitter.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from ._common import (  # noqa: F401  # re-exported helpers are intentional
    Findings,
)

def check_state_page_cross_cites(root: Path, findings: Findings) -> None:
    """VF-FIND-040: the three state-page subskill docs must each cite
    state-page-patterns.md so they don't drift on shared patterns."""
    targets = [
        ("auth-flows.md", root / "04-interaction" / "auth-flows.md"),
        ("system-pages.md", root / "04-interaction" / "system-pages.md"),
        (
            "notifications-and-lifecycle.md",
            root / "04-interaction" / "notifications-and-lifecycle.md",
        ),
    ]
    for name, path in targets:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        if "state-page-patterns" not in text:
            findings.warn(
                f"VF-FIND-040: {name} does not cite state-page-patterns.md. The three "
                f"state-page subskills (auth-flows, system-pages, notifications-and-lifecycle) "
                f"share patterns (re-auth, token-gated link expiry, recovery copy, "
                f"unavailable states); citing the shared reference prevents drift."
            )
