"""File/dir presence checks: required files, persona files, concurrency lock, figma, version stamps, what's-missing, retrofit data awareness.

Generated by scripts/_split_validators.py. Do not hand-edit module structure;
update the source and re-run the splitter.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from ._common import (  # noqa: F401  # re-exported helpers are intentional
    Findings,
    PERSONA_TEMPLATE_A_HEADINGS,
    PERSONA_TEMPLATE_C_HEADINGS,
    REQUIRED_AUDITABILITY,
    REQUIRED_DOCS,
    REQUIRED_TOKENS,
    RETROFIT_REQUIRED,
    ROOT_ALLOWED,
    VERSION_STAMP_PATTERN,
    _extract_h2_headings,
    _heading_matches_required,
)

def check_required_files(root: Path, findings: Findings) -> None:
    for rel in REQUIRED_DOCS + REQUIRED_AUDITABILITY + REQUIRED_TOKENS:
        path = root / rel
        if not path.exists():
            findings.fail(f"Missing required file: {rel}")

    # At least one persona file
    personas_dir = root / "01-foundations" / "personas"
    if personas_dir.exists():
        files = [p for p in personas_dir.glob("persona-*.md")]
        if not files:
            findings.fail("01-foundations/personas/ has no persona-*.md files; expected one per persona.")

    # At least one component file across category subdirs
    comps_root = root / "05-components"
    if comps_root.exists():
        category_files: list[Path] = []
        for cat in ("primitives", "composites", "patterns", "domain"):
            cat_dir = comps_root / cat
            if cat_dir.exists():
                category_files.extend(p for p in cat_dir.glob("*.md") if p.name != "_index.md")
        if not category_files:
            findings.fail(
                "05-components/ has no component files under primitives/composites/patterns/domain."
            )

    # At least one screen file
    screens_dir = root / "06-screens"
    if screens_dir.exists():
        files = [p for p in screens_dir.glob("SCR-*.md")]
        if not files:
            findings.fail("06-screens/ has no SCR-*.md files; expected one per screen.")

    # Anti flat-dump: only ROOT_ALLOWED markdown files at root
    if root.exists():
        for md in root.glob("*.md"):
            if md.name not in ROOT_ALLOWED:
                findings.fail(
                    f"Flat-dump violation: {md.name} sits at design-system root. "
                    f"Move into appropriate sub-folder (01-foundations / 02-visual-language / ...)."
                )

    # Retrofit artifacts if retrofit/ exists
    retrofit_dir = root / "retrofit"
    if retrofit_dir.exists():
        for rel in RETROFIT_REQUIRED:
            path = root / rel
            if not path.exists():
                findings.fail(f"Retrofit mode detected but missing: {rel}")


def check_persona_files(root: Path, findings: Findings) -> None:
    """VF-FIND-004: enforce per-template required sections by filename prefix."""
    personas_dir = root / "01-foundations" / "personas"
    if not personas_dir.exists():
        return
    for path in personas_dir.glob("*.md"):
        if path.name == "_index.md":
            continue
        name = path.name
        text = path.read_text(encoding="utf-8")
        headings = _extract_h2_headings(text)
        rel = path.relative_to(root)
        rel_str = str(rel).replace("\\", "/")
        # Anti-persona: Template B
        if name.startswith("anti-persona-"):
            # Template B requires either "Why she's" OR "Why he's" — relax to either.
            required = {
                "## Identity", "## Context",
                "## What we are intentionally not building",
                "## Anti-persona is binding",
                "## Decision card",
            }
            has_wrong_fit = any(
                h.startswith(prefix)
                for h in headings
                for prefix in (
                    "## Why she's the wrong fit",
                    "## Why he's the wrong fit",
                    "## Why they're the wrong fit",
                )
            )
            missing = _heading_matches_required(headings, required)
            if missing:
                findings.fail(
                    f"Anti-persona file {rel_str} missing required Template-B sections: "
                    f"{sorted(missing)}"
                )
            if not has_wrong_fit:
                findings.fail(
                    f"Anti-persona file {rel_str} missing 'Why … the wrong fit' section "
                    f"(Template B)."
                )
        # Pair scenario: Template C
        elif name.startswith("pair-"):
            missing = _heading_matches_required(headings, PERSONA_TEMPLATE_C_HEADINGS)
            if missing:
                findings.fail(
                    f"Pair-scenario file {rel_str} missing required Template-C sections: "
                    f"{sorted(missing)}"
                )
        # Primary / secondary / edge-case persona: Template A
        elif name.startswith("persona-") or name.startswith("edge-case-"):
            missing = _heading_matches_required(headings, PERSONA_TEMPLATE_A_HEADINGS)
            if missing:
                findings.fail(
                    f"Persona file {rel_str} missing required Template-A sections: "
                    f"{sorted(missing)}"
                )
        else:
            findings.warn(
                f"Persona file {rel_str} has unrecognized prefix; expected "
                f"persona-*, anti-persona-*, edge-case-*, or pair-*-and-*."
            )


def check_concurrency_lock(root: Path, findings: Findings) -> None:
    """If a stale lock file is present, surface it as a warning."""
    lock = root / ".visualforge.lock"
    if lock.exists():
        findings.warn(
            ".visualforge.lock present — verify the last VisualForge run completed cleanly. "
            "Remove the lock if stale."
        )


def check_figma_artifacts(root: Path, findings: Findings) -> None:
    figma_log = root / "auditability" / "figma-build-log.md"
    if not figma_log.exists():
        findings.fail("Missing auditability/figma-build-log.md — Figma build subskill did not run.")
        return
    text = figma_log.read_text(encoding="utf-8")
    if "MCP detection result" not in text:
        findings.warn("figma-build-log.md missing MCP detection result.")
    if "available" not in text and "fallback" not in text:
        findings.warn("figma-build-log.md does not record MCP mode (available/fallback).")
    # If fallback, bundle must exist
    if "fallback" in text:
        bundle = root / "figma-import-bundle"
        if not bundle.exists():
            findings.fail("Figma MCP was unavailable but figma-import-bundle/ does not exist.")


def check_version_stamps(root: Path, findings: Findings) -> None:
    """Every generated narrative doc (outside auditability/, tokens/, figma-import-bundle/,
    retrofit/) must begin with a VisualForge version stamp HTML comment in the first 500 chars."""
    skip_dirs = {"tokens", "auditability", "figma-import-bundle", "retrofit"}
    skip_files = {"WHATS-MISSING.md", "00-index.md", "RULES.md", "HOW-TO-READ.md", "README.md"}
    for path in root.rglob("*.md"):
        rel = path.relative_to(root)
        if any(part in skip_dirs for part in rel.parts):
            continue
        if path.name in skip_files:
            continue
        raw = path.read_text(encoding="utf-8")
        head = raw[:500]
        if not VERSION_STAMP_PATTERN.search(head):
            findings.warn(
                f"Missing VisualForge version stamp at top of "
                f"{str(rel).replace(chr(92), '/')}. Expected `<!-- visualforge: v… run-id=… scope=… generated=… -->`."
            )


def check_whats_missing(root: Path, findings: Findings) -> None:
    """WHATS-MISSING.md must exist and be non-empty."""
    path = root / "WHATS-MISSING.md"
    if not path.exists():
        findings.fail("Missing WHATS-MISSING.md — must be regenerated by design-qa.")
        return
    text = path.read_text(encoding="utf-8")
    if len(text.strip()) < 100:
        findings.warn("WHATS-MISSING.md is suspiciously short; verify it was regenerated.")


def check_retrofit_data_awareness(root: Path, findings: Findings) -> None:
    """In retrofit mode, every screen spec should reference fields from data-inventory."""
    retrofit_dir = root / "retrofit"
    if not retrofit_dir.exists():
        return
    inventory_path = retrofit_dir / "data-inventory.md"
    if not inventory_path.exists():
        return
    inv_text = inventory_path.read_text(encoding="utf-8")
    entity_pattern = re.compile(r"###\s+Entity\s*[—\-]\s*(\w+)", re.IGNORECASE)
    entities = {m.group(1) for m in entity_pattern.finditer(inv_text)}
    if not entities:
        findings.warn(
            "retrofit/data-inventory.md has no '### Entity — Name' sections detected by regex; "
            "data-awareness check skipped."
        )
        return
    screens_dir = root / "06-screens"
    if not screens_dir.exists():
        return
    for screen in screens_dir.glob("SCR-*.md"):
        text = screen.read_text(encoding="utf-8")
        # Heuristic: look for at least one entity.field-style reference.
        ref_pattern = re.compile(r"\b(" + "|".join(re.escape(e) for e in entities) + r")\.\w+\b")
        if not ref_pattern.search(text):
            findings.warn(
                f"Retrofit data-awareness: {screen.name} has no entity.field reference "
                f"to data-inventory entities ({', '.join(sorted(entities))[:80]}…). "
                "Screen specs in retrofit mode should reference real fields."
            )
