"""Token integrity, raw-value scanning in components, dark-mode coverage.

Generated by scripts/_split_validators.py. Do not hand-edit module structure;
update the source and re-run the splitter.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from ._common import (  # noqa: F401  # re-exported helpers are intentional
    CUBIC_PATTERN,
    Findings,
    HEX_PATTERN,
    RAW_MS_PATTERN,
    RAW_PX_PATTERN,
    REF_PATTERN,
    flatten_tokens,
    load_tokens,
)

def check_token_integrity(root: Path, findings: Findings) -> dict[str, str]:
    tokens = load_tokens(root)
    if tokens is None:
        return {}
    if "__error__" in tokens:
        findings.fail(f"tokens.json is not valid JSON: {tokens['__error__']}")
        return {}
    flat = flatten_tokens(tokens)
    for path, value in flat.items():
        match = REF_PATTERN.match(value)
        if match:
            target = match.group(1)
            if target not in flat:
                findings.fail(f"Unresolved token reference: {path} -> {{{target}}}")
    return flat


def check_no_raw_values_in_components(root: Path, findings: Findings) -> None:
    """Component docs should reference tokens, not raw hex / px / ms / cubic-bezier."""
    comp_root = root / "05-components"
    if not comp_root.exists():
        return
    # Aggregate all component markdown files across categories.
    files: list[Path] = list(comp_root.rglob("*.md"))
    if not files:
        return
    text = "\n".join(p.read_text(encoding="utf-8") for p in files)
    for pattern, label in [
        (HEX_PATTERN, "raw hex color"),
        (RAW_PX_PATTERN, "raw px value"),
        (RAW_MS_PATTERN, "raw ms duration"),
        (CUBIC_PATTERN, "raw cubic-bezier"),
    ]:
        for m in pattern.finditer(text):
            # ignore inside code fences or token paths
            ctx_start = max(0, m.start() - 40)
            context = text[ctx_start:m.start()]
            if "`" in context and context.rfind("`") > context.rfind("\n"):
                continue
            line_no = text[: m.start()].count("\n") + 1
            findings.warn(
                f"Possible {label} in component docs at line {line_no}: "
                f"'{m.group(0)}' — should reference a token."
            )


def check_dark_mode_coverage(flat_tokens: dict[str, str], findings: Findings) -> None:
    """Semantic surface / text / border / accent tokens should have dark variants documented."""
    if not flat_tokens:
        return
