"""v1.8.0 visual-default-breaker checks: hero scale, image art direction, platform mode, lock completeness, React quality, persona validation, pressure-test reviewers, timing-token drift.

Generated by scripts/_split_validators.py. Do not hand-edit module structure;
update the source and re-run the splitter.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

from ._common import (  # noqa: F401  # re-exported helpers are intentional
    Findings,
    REQUIRED_AUDITABILITY,
    _TIMING_TOKEN_DECL_PATTERN,
)

def check_visual_default_breakers(root: Path, findings: Findings) -> None:
    """VF-FIND-032: enforce the visual-default-breaker decision cards / sections.

    - brand-identity.md must reference a Hero Scale decision (DEC-098 or text).
    - brand-identity.md must reference a default Hero Composition Anchor (DEC-099 or text).
    - brand-identity.md must reference a Narrative / concept spine (DEC-100 or text).
    - layout-system.md must contain a "Composition anchor" inventory.
    - layout-system.md must contain a "Cross-section variety" rule.
    - surface-treatments.md must enumerate "Banned" gradient patterns.

    Each missing piece is a WARN. Files that don't exist are not this check's job
    (check_required_files handles existence).
    """
    bi = root / "02-visual-language" / "brand-identity.md"
    ls = root / "03-structure" / "layout-system.md"
    st = root / "02-visual-language" / "surface-treatments.md"

    if bi.exists():
        bi_text = bi.read_text(encoding="utf-8")
        if "Hero Scale" not in bi_text and "Hero scale" not in bi_text:
            findings.warn(
                "VF-FIND-032: brand-identity.md missing Hero Scale decision "
                "(expected DEC-098 or a 'Hero Scale' section). "
                "Hero Scale is required per visual-default-breakers.md §2."
            )
        if "Composition Anchor" not in bi_text and "composition anchor" not in bi_text:
            findings.warn(
                "VF-FIND-032: brand-identity.md missing default Hero Composition Anchor "
                "(expected DEC-099 or a 'Composition Anchor' section). "
                "Required per visual-default-breakers.md §1."
            )
        if "Narrative" not in bi_text and "narrative spine" not in bi_text.lower():
            findings.warn(
                "VF-FIND-032: brand-identity.md missing Narrative / concept spine "
                "(expected DEC-100 or a 'Narrative' section). "
                "Required per visual-default-breakers.md §14."
            )

    if ls.exists():
        ls_text = ls.read_text(encoding="utf-8")
        if "Composition anchor" not in ls_text and "composition-anchor" not in ls_text.lower():
            findings.warn(
                "VF-FIND-032: layout-system.md missing Composition anchor inventory "
                "(expected section listing the 9 anchors). "
                "Required per visual-default-breakers.md §4."
            )
        if "Cross-section variety" not in ls_text and "cross-section" not in ls_text.lower():
            findings.warn(
                "VF-FIND-032: layout-system.md missing Cross-section variety rule. "
                "Required per visual-default-breakers.md §4 and §5."
            )

    if st.exists():
        st_text = st.read_text(encoding="utf-8")
        # Must explicitly enumerate banned gradient patterns (not just mention).
        has_banned_section = (
            "Banned gradient" in st_text
            or "banned gradient" in st_text.lower()
            or "Banned (AI gradient slop)" in st_text
        )
        if not has_banned_section:
            findings.warn(
                "VF-FIND-032: surface-treatments.md does not enumerate banned gradient "
                "patterns. Required per visual-default-breakers.md §6 — must list "
                "purple-to-blue, pink-to-orange, rainbow / mesh blob gradients by name."
            )


def check_image_art_direction(root: Path, findings: Findings) -> None:
    """VF-FIND-033: imagery-illustration.md must contain the Section 0 image
    art-direction layer (background mode inventory + image-led posture)."""
    p = root / "04-interaction" / "imagery-illustration.md"
    if not p.exists():
        return
    text = p.read_text(encoding="utf-8")
    has_bg_inventory = "Background mode" in text or "background mode" in text.lower()
    has_section_0 = "### 0." in text or "Image art-direction" in text or "image art direction" in text.lower()
    if not (has_bg_inventory and has_section_0):
        findings.warn(
            "VF-FIND-033: imagery-illustration.md missing Section 0 (image art-direction "
            "with background-mode inventory). Required per visual-default-breakers.md §5."
        )


def check_platform_mode_lock(root: Path, findings: Findings) -> None:
    """VF-FIND-034: mobile-and-responsive.md must contain a Platform mode lock
    section (Section 0) committing to iOS-native / Android-native / cross-platform."""
    p = root / "03-structure" / "mobile-and-responsive.md"
    if not p.exists():
        return
    text = p.read_text(encoding="utf-8")
    has_lock = (
        "Platform mode lock" in text
        or "platform mode lock" in text.lower()
        or "platform-mode lock" in text.lower()
    )
    if not has_lock:
        findings.warn(
            "VF-FIND-034: mobile-and-responsive.md missing Platform mode lock (Section 0). "
            "Required per visual-default-breakers.md and mobile platform discipline."
        )


def check_visual_direction_lock_complete(root: Path, findings: Findings) -> None:
    """VF-FIND-035: visual-direction-lock.md must exist and have every required
    commitment filled (no `[...]` placeholders left from the template).

    Existence is enforced by check_required_files (REQUIRED_AUDITABILITY). This
    check verifies completeness — required commitment sections must be present
    AND must not contain unresolved `[...]` placeholder slots.
    """
    p = root / "auditability" / "visual-direction-lock.md"
    if not p.exists():
        return  # existence handled elsewhere
    text = p.read_text(encoding="utf-8")
    required_commitments = [
        "Theme paradigm",
        "Typography character",
        "Hero scale",
        "Hero composition anchor",
        "Narrative",
        "Background mode",
        "Signature components",
        "Motion-implied",
        "Second-read moment",
        "Banned-by-default",
    ]
    missing = [c for c in required_commitments if c.lower() not in text.lower()]
    if missing:
        findings.warn(
            f"VF-FIND-035: visual-direction-lock.md missing commitment sections: "
            f"{missing}. Required per orchestrator Step 0g."
        )
    # Detect unresolved `[...]` placeholders. Tolerate `[ ]` checkboxes (Markdown).
    # Look for the template's literal placeholder shape: `[name + rationale]`,
    # `[name + 1-sentence rationale tied to brand attribute]`, etc.
    placeholder_pattern = re.compile(r"\*\*Chosen:\*\*\s*\[")
    if placeholder_pattern.search(text):
        findings.warn(
            "VF-FIND-035: visual-direction-lock.md contains unresolved `[...]` "
            "placeholders (template values not filled in). Required per orchestrator "
            "quality-gate-before-completion."
        )


def check_react_quality_discipline(root: Path, findings: Findings) -> None:
    """VF-FIND-036: frontend-contract.md must contain the React-quality discipline
    section (§17 or named heading 'React quality discipline')."""
    p = root / "07-quality" / "frontend-implementation-contract.md"
    if not p.exists():
        return
    text = p.read_text(encoding="utf-8")
    has_section = (
        "React quality discipline" in text
        or "React / framework quality discipline" in text
        or "React boundaries" in text
    )
    if not has_section:
        findings.warn(
            "VF-FIND-036: frontend-implementation-contract.md missing React quality "
            "discipline section (§17). Required — token pipeline + bundler config "
            "alone do not enforce React boundaries / state / form / data discipline."
        )


def check_assumption_persona_validation(root: Path, findings: Findings) -> None:
    """VF-FIND-037: any persona file labeled `Source basis: Assumption` or
    `Confidence: Low` must contain a Validation plan section that names a
    research method from the user-research method ladder."""
    personas_dir = root / "01-foundations" / "personas"
    if not personas_dir.exists():
        return
    method_keywords = [
        "interview",
        "usability testing",
        "usability test",
        "survey",
        "card sort",
        "diary",
        "a/b test",
        "analytics cohort",
        "support ticket",
        "support-ticket",
    ]
    # Match markdown-bold variants like `**Source basis:** Assumption`.
    assumption_pattern = re.compile(
        r"Source\s+basis\s*:?\*{0,2}\s*\*{0,2}\s*Assumption", re.IGNORECASE
    )
    low_conf_pattern = re.compile(
        r"Confidence\s*:?\*{0,2}\s*\*{0,2}\s*Low", re.IGNORECASE
    )
    for persona in personas_dir.glob("persona-*.md"):
        text = persona.read_text(encoding="utf-8")
        is_assumption = (
            assumption_pattern.search(text) is not None
            or low_conf_pattern.search(text) is not None
        )
        if not is_assumption:
            continue
        # Find the Validation plan section
        plan_match = re.search(
            r"##\s+Validation plan(.*?)(?=^##\s|\Z)", text, re.MULTILINE | re.DOTALL
        )
        if not plan_match:
            findings.warn(
                f"VF-FIND-037: persona '{persona.name}' is Assumption/Low-confidence "
                f"but has no Validation plan section."
            )
            continue
        plan_text = plan_match.group(1).lower()
        if not any(kw in plan_text for kw in method_keywords):
            findings.warn(
                f"VF-FIND-037: persona '{persona.name}' Validation plan does not name a "
                f"method from the research-method ladder (interview / usability test / "
                f"survey / card sort / diary / A/B / cohort / tickets)."
            )


def check_pressure_test_reviewer_coverage(root: Path, findings: Findings) -> None:
    """VF-FIND-038: design-pressure-test-report.md Pass L must include the new
    Visual-direction critic and React-product-fit critic rows."""
    p = root / "07-quality" / "design-pressure-test-report.md"
    if not p.exists():
        return
    text = p.read_text(encoding="utf-8")
    # Only enforce on reports that include a Pass L section; an earlier-phase report
    # may legitimately not yet have Pass L.
    if "Pass L" not in text and "Multi-expert" not in text:
        return
    missing = []
    if "Visual-direction critic" not in text:
        missing.append("Visual-direction critic")
    if "React-product-fit critic" not in text:
        missing.append("React-product-fit critic")
    if missing:
        findings.warn(
            f"VF-FIND-038: design-pressure-test-report.md Pass L missing reviewer "
            f"rows: {missing}. Required per v1.8.0 — these two lenses catch visual "
            f"defaults and React anti-patterns the existing 6 reviewers miss."
        )


def check_timing_token_drift(root: Path, findings: Findings) -> None:
    """VF-FIND-039: motion-design.md is the source-of-truth for duration / easing
    tokens. micro-interactions.md and scroll-and-gesture.md must not redeclare
    the same token with a different numeric value.
    """
    motion = root / "04-interaction" / "motion-design.md"
    if not motion.exists():
        return
    motion_text = motion.read_text(encoding="utf-8")
    motion_tokens: dict[str, str] = {}
    for m in _TIMING_TOKEN_DECL_PATTERN.finditer(motion_text):
        token, value = m.group(1).lower(), m.group(2)
        motion_tokens.setdefault(token, value)
    if not motion_tokens:
        return

    consumers = [
        ("micro-interactions.md", root / "04-interaction" / "micro-interactions.md"),
        ("scroll-and-gesture.md", root / "04-interaction" / "scroll-and-gesture.md"),
    ]
    for name, path in consumers:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        for m in _TIMING_TOKEN_DECL_PATTERN.finditer(text):
            token, value = m.group(1).lower(), m.group(2)
            if token in motion_tokens and motion_tokens[token] != value:
                findings.warn(
                    f"VF-FIND-039: timing-token drift — {name} declares `{token}` as "
                    f"{value}ms but motion-design.md (source of truth) declares it as "
                    f"{motion_tokens[token]}ms. {name} must cite the motion-design "
                    f"value, not redeclare it."
                )
